sudo: required
services: 
  - docker

before_install: 
  - docker build -t ahmedgrissa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ahmedgrissa/frontend npm run test -- --coverage
